sonar.projectKey=cagatayuresin_md2cv
sonar.organization=cagatayuresin
sonar.projectName=md2cv
sonar.projectVersion=2.0.0

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=app/web/**,examples/**,output/**,templates/**,docs/**
sonar.coverage.exclusions=app/__init__.py,app/main.py,app/cli.py
